import { Role } from './types';

export const ROLES: Role[] = [
  {
    id: 'magang',
    name: 'Si Anak Magang',
    nickname: 'The Grinder',
    description: 'Pekerja keras yang selalu lembur.',
    passive: 'Jika dadu Ganjil, ambil Rp50rb dari Bank (Uang Lembur).',
    color: '#6B7280',
  },
  {
    id: 'creator',
    name: 'Content Creator',
    nickname: 'The Influencer',
    description: 'Selebgram yang pengaruhnya besar.',
    passive: 'Diskon sewa 25% di petak Merah & Kuning.',
    debuff: 'Bayar pajak 2x lipat.',
    color: '#EC4899',
  },
  {
    id: 'parkir',
    name: 'Tukang Parkir',
    nickname: 'The Gatekeeper',
    description: 'Jaga parkir, cari celah.',
    passive: 'Dapat Rp50rb dari pemain yang berhenti di petak Transportasi manapun.',
    color: '#F59E0B',
  },
  {
    id: 'olshop',
    name: 'Admin Olshop',
    nickname: 'The Fast Response',
    description: 'Respon cepat, uang banyak.',
    passive: 'Tambahan Rp200rb di START.',
    debuff: 'Kena denda Rp100rb jika masuk Dana Umum.',
    color: '#8B5CF6',
  },
  {
    id: 'rt',
    name: 'Ketua RT',
    nickname: 'The Local Leader',
    description: 'Bapak RT yang berkuasa.',
    passive: 'Bebas sewa di petak Cokelat & Light Blue milik lawan. Dapat Rp50rb jika orang mendarat di propertimu.',
    color: '#10B981',
  },
  {
    id: 'travel',
    name: 'Supir Travel',
    nickname: 'The Navigator',
    description: 'Jalan sudah hafal di luar kepala.',
    passive: 'Bisa memajukan/memundurkan bidak 1 langkah dari hasil dadu (3x pakai).',
    color: '#3B82F6',
  },
  {
    id: 'sultan',
    name: 'Sultan Gadungan',
    nickname: 'The Flexer',
    description: 'Hutang banyak gaya banyak.',
    passive: 'Bisa beli properti meski uang minus (hutang).',
    debuff: 'Bunga hutang 20% per putaran.',
    color: '#D4A017',
  },
  {
    id: 'aktivis',
    name: 'Aktivis Sosmed',
    nickname: 'The Canceller',
    description: 'Ancaman viralin selalu ampuh.',
    passive: 'Bebas sewa di properti lawan yang level 3 ke atas (Ancaman Viralin).',
    color: '#EF4444',
  },
  {
    id: 'gorengan',
    name: 'Penjual Gorengan',
    nickname: 'The Survivor',
    description: 'Tahan banting, murah meriah.',
    passive: 'Kebal terhadap kartu Dana Umum yang bersifat denda/merugikan.',
    color: '#A16207',
  },
  {
    id: 'kripto',
    name: 'Investor Kripto',
    nickname: 'The Speculator',
    description: 'High risk high reward.',
    passive: 'Di START, lempar dadu. 1-3: Rugi Rp500rb. 4-6: Cuan Rp1 Juta.',
    color: '#06B6D4',
  },
];
